### ISSUE TITLE
Rewrite it in Rust

### ISSUE THREAD

**Issue by Desiders** [zigpython/zpython#4]
Implementing Python in Rust rather than Zig offers several advantages:

    Performance: Rust's performance is often comparable to C and C++, making it an excellent choice for implementing performance-sensitive components of Python interpreters. Its zero-cost abstractions and efficient memory management can lead to faster execution compared to Zig.

    Safety: Rust's ownership system and extensive compile-time checks ensure memory safety and prevent common bugs like null pointer dereferences and data races. This reduces the risk of crashes and vulnerabilities in Python interpreters implemented in Rust.

    Ecosystem: Rust has a growing ecosystem with a wide range of libraries and tools, making it easier to implement and maintain Python interpreters. This rich ecosystem includes libraries for parsing, code generation, and optimization, which can accelerate the development process.

    Concurrency: Rust's ownership system allows for safe and efficient concurrency, which is crucial for building scalable and responsive Python interpreters. Rust's async/await syntax simplifies asynchronous programming, enabling Python interpreters to handle concurrent tasks more effectively.

    Community Support: Rust has a vibrant and active community that provides extensive documentation, tutorials, and support resources. This makes it easier for developers to implement Python interpreters in Rust and address any challenges they encounter along the way.

Overall, while Zig offers similar benefits in terms of performance and safety, Rust's mature ecosystem and strong community support make it a compelling choice for implementing Python interpreters, particularly for projects that prioritize performance, safety, and scalability.

**Comment by wrongnull** [comment]
I'm sure the SDDDYY architecture is much easier to implement in zig.

**Comment by Desiders** [comment]
> I'm sure the SDDDYY architecture is much easier to implement in zig.

You're right
